export const LOAD_PRIVACY_POLICY_PENDING =
  'app/PrivacyPolicy/LOAD_PRIVACY_POLICY_PENDING';
export const LOAD_PRIVACY_POLICY_SUCCESS =
  'app/PrivacyPolicy/LOAD_PRIVACY_POLICY_SUCCESS';
export const LOAD_PRIVACY_POLICY_FAILED =
  'app/PrivacyPolicy/LOAD_PRIVACY_POLICY_FAILED';
